name: cat
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  intl: ^0.17.0
  hive:
  hive_flutter:
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
